In [1]:
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
curr_dir = os.getcwd()
path = os.path.join(curr_dir, '../train.csv')
data = pd.read_csv(path)

data = np.array(data)
m, n = data.shape # m is the rows, n is columns
np.random.shuffle(data)

In [3]:
data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.

In [7]:
print("Data")
print("X_train: ", X_train)
print("Y_train: ", Y_train)

# x is the pixel data by row
# y is the label of the data

Data
X_train:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Y_train:  [3 1 5 ... 8 6 3]


In [5]:
print("Shape of data")
print("X_train: ", X_train.shape)
print("Y_train: ", Y_train.shape)

Shape of data
X_train:  (784, 41000)
Y_train:  (41000,)


In [6]:
print("Pixel data for 1st image: ", X_train[0])
print("Shape of image data: ", X_train[0].shape)

Pixel data for 1st image:  [0. 0. 0. ... 0. 0. 0.]
Shape of image data:  (41000,)
